### ISSUE TITLE
Different column destination? is it posible?

### ISSUE THREAD

**Issue by abriosso** [mrjgreen/db-sync#10]
I am trying to sync to different databases, with different tables and different column names. I s it possible to reference different columns to sync?

**Comment by mrjgreen** [comment]
No, unfortunately not different column names. 

In this case you could try the following: 
- create a clone of your source table in the target database
- add a column 'date_updated timestamp ON UPDATE CURRENT_TIMESTAMP' to the new target table
- sync to this table
- after the sync has completed run an update with a join to copy from the new table to your real target table, where the date last update is newer than the time at which you started the dbsync to copy any modified rows into whatever column names you like. 

Cheers
Joe Green
