### ISSUE TITLE
Is it compatible with MS Windows?

### ISSUE THREAD

**Issue by Xperianet** [mrjgreen/db-sync#14]
Can I use DB-Sync on Windows, what steps needed to port it to Windows? The binary .phar seems to target Linux only?

**Comment by mrjgreen** [comment]
I'm not sure how easy/hard this would be to get running on windows... I've never tested it... 

What do you see failing? As far as I know there's nothing specific to linux in the code base.

You should be able to execute the db-sync.phar using: `php /path/to/db-sync.phar`

**Comment by Xperianet** [comment]
@mrjgreen Thanks, it works well in Windows as well, I have tested. I thought before that the binary is of ELF format, which is not true.

**Comment by mrjgreen** [comment]
Great!
