### ISSUE TITLE
Composer: Uncaught Error: Class 'DBSync\DbSync' not found

### ISSUE THREAD

**Issue by dotnetCarpenter** [mrjgreen/db-sync#16]
Hi, I'm completely new to composer, so I do not know if this is an issue with how *db-sync* is configured or how I use composer. I suspect it's the latter, but anyhow it could be an idea to include the answer in the *README* for other composer newbies.

When I do `new DBSync()` I get a fatal error. Here is a quick test of what I'm doing:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use DbSync\Hash\ShaHash;
use DBSync\DbSync;

new ShaHash();
new DBSync(); // this fails with Class 'DBSync\DbSync' not found in /.../sync/sync.php:8
?>
```

Note that the `new ShaHash();` line seems to work just fine.

**Comment by nztim** [comment]
Try correcting the capitalization:

```
use DbSync\DbSync; 
new DbSync();
```

**Comment by dotnetCarpenter** [comment]
Damn! I completely missed that. Thanks @nztim

**Comment by dotnetCarpenter** [comment]
For future reference:

```php
#!/usr/bin/php

<?php

	require __DIR__ . '/vendor/autoload.php';

	use DbSync\DbSync;
	use DbSync\Transfer\Transfer;
	use DbSync\Hash\ShaHash;

	
  	$sync = new DBSync(new Transfer(new ShaHash()));
	$sync->dryRun();
        ....
?>
```

**Comment by mrjgreen** [comment]
Thanks for the comments guys, I'm glad you got it working.

I've updated the readme with the use statements - hope that helps!
