### ISSUE TITLE
The "target.pass" option does not exist.

### ISSUE THREAD

**Issue by dotnetCarpenter** [mrjgreen/db-sync#17]
I'm trying to sync a remote db with my local db and are getting `The "target.pass" option does not exist`.

I have installed *db-sync* via *composer* are using version `v3.2.0` on Linux.

My sync command looks like this:

```
./vendor/bin/sync -v --user USERNAME --password PASSWORD 1.2.3.4 127.0.0.1 dbname.bs_users
```

My local and remote db share the same credentials. I've tried to be more explicit and declare `target.password` but I get the same error message.

How can I debug this?

OUTPUT: 

```
Reading ini file 'dbsync.ini'
The "target.pass" option does not exist.
#0 /var/www/trustpet.dk/sql_dumps/sync/vendor/mrjgreen/db-sync/src/Command/SyncCommand.php(116): Symfony\Component\Console\Input\Input->setOption('target.pass', 'cassandra457')
#1 /var/www/trustpet.dk/sql_dumps/sync/vendor/symfony/console/Command/Command.php(265): DbSync\Command\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/trustpet.dk/sql_dumps/sync/vendor/mrjgreen/db-sync/bin/sync(76): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/trustpet.dk/sql_dumps/sync/vendor/mrjgreen/db-sync/bin/sync(92): DbSync\Command\App->run(Object(DbSync\Command\SyncCommand))
#4 {main}
```

**Comment by mrjgreen** [comment]
EDIT - Hope you don't mind but I've ninja edited your comment to remove the IP address and database :)

`target.pass` is not a valid option, the correct option is `target.password`, but you say that isn't working either?

I can see from the output that you are using a `dbsync.ini` file.  Could you please post the contents of that, being very careful to replace the username and password with a placeholder value.

Thanks

**Comment by dotnetCarpenter** [comment]
The content of dbsync.ini:

```
user=USERNAME
password=PASSWORD
target.user=USERNAME
target.pass=PASSWORD
```

I see my error now. `target.pass` should have been `target.password`.

Renaming `dbsync.ini`, made  the issue go away.

The reason I used `target.pass` is because it is what it says in the README: https://github.com/mrjgreen/db-sync/#config-file

Would be nice if you changed that :)

**Comment by mrjgreen** [comment]
Ahh yes, thanks for spotting that!

I've updated the readme.
