### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by sachin0606** [mrjgreen/db-sync#19]
Thannks for the code, 

i am new to php. and developing one phonegap application . so any idea how can i send table to this code from my application?

and is this worth to send total table to server ?

**Comment by mrjgreen** [comment]
I don't think this is the right use case for this tool. I'm not sure exactly what you are trying to do, but I suspect you want to host your database centrally and send data from your app via some API.

Let me know if you have any other questions about DbSync use cases!
