### ISSUE TITLE
from source column X to target column Y

### ISSUE THREAD

**Issue by travis-r6s** [mrjgreen/db-sync#21]
I have seen there is an option to change the target table, is there a way to change the target column?
So for example I have might have app.users with -c username , and i would like to it to copy that to app2.users -c uid.

**Comment by mrjgreen** [comment]
I think this question is a clone of #10. Have a read of it and let me know if it answers your question!

**Comment by travis-r6s** [comment]
sorry, yes it was..... I will look closer at previous issues in future! Thanks
