### ISSUE TITLE
How to use --where= in command line

### ISSUE THREAD

**Issue by rafaelcarsetimo** [mrjgreen/db-sync#27]
Im trying the syntax:

db-sync -e --user root --password PASSWORD origin.server.com destiny.server.com:3306 database.table --target.user=remoteuser --target.password='REMOTEPASSWORD' --target.table=database.table --where=date='2017-06-18'

In my table I have a columm date with this data, but the --where cant find.

[info] Hash calculation:

CONCAT(COALESCE(LOWER(CONV(BIT_XOR(CAST(CONV(SUBSTR(MD5(CONCAT_WS('#', `id`, `cliente`, `date`, `hour`, `ethport`, `ethalias`, `direction`, `bytes`)),17,16),16,10) AS UNSIGNED)), 10, 16)), 0),COALESCE(LOWER(CONV(BIT_XOR(CAST(CONV(SUBSTR(MD5(CONCAT_WS('#', `id`, `cliente`, `date`, `hour`, `ethport`, `ethalias`, `direction`, `bytes`)),1,16),16,10) AS UNSIGNED)), 10, 16)), 0))
[info] Written '0' rows, checked '1024' rows for tables 'table' => 'database.table'
[notice] {"checked":1024,"transferred":0,"affected":0} 

![capture](https://user-images.githubusercontent.com/21690644/27312755-beb0f95e-5540-11e7-89de-18217175aa47.PNG)

Thanks in advance.

Rafael.

**Comment by mrjgreen** [comment]
I'm not 100% sure about this... are you getting an error or just no results? Try running the command in verbose mode: `db-sync -v -e --user....` and looking at the queries its executing.

Its possible that wrapping the where clause in quotes will help:

    db-sync -e --user root --password PASSWORD origin.server.com destiny.server.com:3306 database.table --target.user=remoteuser --target.password='REMOTEPASSWORD' --target.table=database.table --where="date = '2017-06-18'"

The other thing to watch out for here is that `date` and `hour` are functions in MySQL. DbSync should be able to handle that, but in general its best to avoid naming your columns with reserved words as it always catches you out at some point :)

**Comment by rafaelcarsetimo** [comment]
Awesome!

--where="date = '2017-06-18'" WORKS!

Thanks a LOT!

Rafael.

**Comment by mrjgreen** [comment]
Thanks, I've added an example for this in the readme: https://github.com/mrjgreen/db-sync/commit/df3c64701d7071153f45b2994dc24d8cf3ea2562
