### ISSUE TITLE
ini file aborts script

### ISSUE THREAD

**Issue by damelco** [mrjgreen/db-sync#28]
I am having a problem using an ini file for the connection criteria
both in using a default 'dbsync.ini' and the same result using the '--config-file my-cfg.ini' option
I have verified a working command line, however when I move that config data into a *.ini file the script seems to abort right after the message;
Reading ini file 'my-cfg.ini.ini'
--verbose displays nothing additional.
though
-v does trigger a display of
ea-php-cli Copyright 2017 cPanel, Inc.

oddly ... if I leave the --execute off the command, I do get;
[notice] Dry run only. No data will be written to target.

when using without an ini file and --verbose the next line is;
[info] Hash calculation:
with the ini file neither that or anything else is displayed following the reading of the ini and Dry run notice.

*** EDIT ***
 not sure if this should be a separate post ... but IS related to the the reading of the ini file.
the password string is rejected if includes certain characters. double quotes and carats for sure ... possibly others? though that same password string works fine via command line without ini.

**Comment by damelco** [comment]
any update on this?
any additional information needed?

we would surely like to use this handy script and attach it via cron ... we hesitate to do so via individual command-lines.

thanks

**Comment by mrjgreen** [comment]
Judging by the error message (contains the words "ea-php-cli Copyright 2017 cPanel, Inc."), it looks like the issue you are having is related to the platform you are running this on. It doesn't look like db-sync is being executed properly. Unfortunately there isn't enough info here for me to help diagnose the exact issue... is there anything else you can provide?

**Comment by damelco** [comment]
I am a linux novice, so not really sure what else might be useful?!?!

CentOS release 6.9 (Final)

BlueHost VPS host running cPanel v. 11.66

ea-php-cli Copyright 2017 cPanel, Inc.
PHP 7.0.26 (cli) (built: Dec  4 2017 16:05:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.1.0 (), Copyright (c) 2002-2017, by ionCube Ltd.

if there is something specific that would assist you in finding a solution, just ask!

**Comment by mrjgreen** [comment]
I'm going to close this issue for now - seems like you might be having problems with a specific host provider and I don't think I'm going to be able to help

**Comment by halcoolllc** [comment]
it is fixed. Actually it is not the code issue. it is about the mysql
version issue. Basically higher mysql version has more restriction on the
date with null value and it mesed up there. if you turn such off and the
code runs good. Thanks!

Shenghua Li, CEO
Halcool LLC
Tel: 408.320.6582
email: halcoolllc@gmail.com
