### ISSUE TITLE
db-sync3 error

### ISSUE THREAD

**Issue by ruslan-ushakov** [mrjgreen/db-sync#3]
Hi! I get an error when calling the commands.

Command:

c:\server\OpenServer\domains\mysite.com>php console\tools\db-sync3.phar --user root --pass 123 127.0.0.1 --target.user root 127.0.0.1 table_source.service --target.table 
  table_destination.service

Error:
Fatal error: Call to undefined function DbSync\Command\posix_getpwuid() in phar://C:/server/OpenServer/domains/mysite.com/console/tools/db-sync3.phar/src/Command/SyncCommand.php on line 35

**Comment by mrjgreen** [comment]
Ahh sorry windows :) this probably will only work with the posix lib compiled. 

I'll push an update in 10 mins. 

Cheers
Joe Green

**Comment by mrjgreen** [comment]
Okay that should be sorted. 

I'll add some additional tests for the command setup soon.
