### ISSUE TITLE
Correct db-sync code for PHP version (correcting DbSync\Transfer error)

### ISSUE THREAD

**Issue by bakjanos** [mrjgreen/db-sync#31]
Hello,
The original code is giving error while loading DbSync\Transfer. The reason is that the file is here:
DbSync\Transfer\Transfer.
The correct code (for at least Windows installation with composer):

require 'C:\Users\Administrator\vendor\autoload.php';

use DbSync\DbSync;
use DbSync\Transfer\Transfer;
use DbSync\Hash\ShaHash;
use DbSync\Table;
use DbSync\ColumnConfiguration;

$blockSize = 1024;
$transferSize = 128;
$sourceDb = "dbname";
$sourceHost = "sourcehost";
$sourceUser = "user";
$sourcePassword = "pw";
$targetDb = "dbname";
$targetHost = "targethost";
$targetUser = "name";
$targetPassword = "user";

$shah = new ShaHash();
$trf = new Transfer($shah, $blockSize, $transferSize);
$sync = new DbSync($trf);

// $sync->setLogger(new YourPsrLogger());

$sync->dryRun(false);
$sync->delete(true);

$factory = new \Database\Connectors\ConnectionFactory();

$sourceConnection = $factory->make(array(
    'driver'    => 'mysql',
    'host'      => $sourceHost,
    'username'  => $sourceUser,
    'password'  => $sourcePassword,
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',

    // Don't connect until we execute our first query
    'lazy'      => true,

    // Set PDO attributes after connection
    'options' => array(
        PDO::MYSQL_ATTR_LOCAL_INFILE    => true,
        PDO::ATTR_EMULATE_PREPARES      => true,
    )
));
$targetConnection = $factory->make(array(
    'driver'    => 'mysql',
    'host'      => $targetHost,
    'username'  => $targetUser,
    'password'  => $targetPassword,
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',

    // Don't connect until we execute our first query
    'lazy'      => true,

    // Set PDO attributes after connection
    'options' => array(
        PDO::MYSQL_ATTR_LOCAL_INFILE    => true,
        PDO::ATTR_EMULATE_PREPARES      => true,
    )
));

// if you only want specific columns 
// $columnConfig = new ColumnConfiguration($syncColumns, $ignoreColumns);

// optionally apply a where clause - this can be useful when sync-ing large tables, where
// you can make use of a column to rule out large portions of the data
// that you know haven't changed, such as columns with "on update CURRENT_TIMESTAMP" etc..
// $sourceTable->setWhereClause(new WhereClause("column_name = ?", ['value']));
// $targetTable->setWhereClause(new WhereClause("column_name > ?", ['value']));

$sourceTab = "tablename";
$sourceTable = new Table($sourceConnection, $sourceDb, $sourceTab);
$targetTable = new Table($targetConnection, $targetDb, $sourceTab);
$sync->sync($sourceTable, $targetTable ); //, $columnConfig);
echo "$sourceTab  syncronised<br>";

// Tested and working!

**Comment by rutvij2292** [comment]
Thanks, @bakjanos Example is Helpful for a windows machine user. @mrjgreen Thanks for this awesome library. I am having a hard time to set up a master-slave replication in MySQL. This library is a time saver. Is this recommended for large traffic site as well? 

Currently, I am planning to apply whereClause on the timestamp. Will it be problematic? Please let me know. Once again thanks, guys.

**Comment by elielmathe** [comment]
Thanks a lot.
I am not very good at composer and I could not troubleshoot the code on main README.
My suggestion is that they edit the code in the README.

**Comment by elielmathe** [comment]
@rutvij2292 
For high trafic applications, I can suggest that you create a table in your MySQL Schema called Synchronised then you record the last synchronised id.
On the next synchronisation, get the last synchronised id for the table and add 
`--where idInTable>previousLastSyncedId`
I assume that you work on INSERTS because this is a problem when dealing with UPDATE and DELETE.

**Comment by elielmathe** [comment]
Oh, sorry, this is related to the CLI.
For integration in PHP, use
$sourceTable->setWhereClause(new WhereClause("idInTable > ?", [previousLastSyncedId]));

**Comment by mrjgreen** [comment]
Thanks, I've updated the use statement in the readme: https://github.com/mrjgreen/db-sync/commit/0c50c4680f789e3ff356a7f7d8535491ca6ad0f6

**Comment by rutvij2292** [comment]
@elielmathe Make sense. Thanks for pointing that out. One last question Should I sync manually or should I go for the MySQL Master Slave replication? I am open to any suggestions. 
Once again thanks for your input.
