### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by mkoivuporras** [mrjgreen/db-sync#34]
I have a problem that is most likely just a stupid user error, but it would be nice to have some help with this. 

Mysql is working ok

`sudo ./db-sync 127.0.0.1 xxx.xxx.xxx.xxx sync_testi.sync1`
`Connection to 'mysql:host=127.0.0.1;port=3306' failed: could not find driver`
`#0 phar:///home/pi/db-sync/db-sync/vendor/mrjgreen/database/src/Connectors/MySqlConnector.php(21): Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)`
`#1 phar:///home/pi/db-sync/db-sync/vendor/mrjgreen/database/src/Connectors/ConnectionFactory.php(119): Database\Connectors\MySqlConnector->connect(Array)`
`#2 phar:///home/pi/db-sync/db-sync/vendor/mrjgreen/database/src/Connectors/ConnectionFactory.php(97): Database\Connectors\ConnectionFactory->createSingleConnection(Array, false)`
`#3 phar:///home/pi/db-sync/db-sync/vendor/mrjgreen/database/src/Connectors/ConnectionFactory.php(77): Database\Connectors\ConnectionFactory->makeConnection(Array, false)`
`#4 phar:///home/pi/db-sync/db-sync/src/Command/SyncCommand.php(220): Database\Connectors\ConnectionFactory->make(Array)`
`#5 phar:///home/pi/db-sync/db-sync/src/Command/SyncCommand.php(148): DbSync\Command\SyncCommand->createConnection('127.0.0.1', 'root', NULL, 'utf8')`
`#6 phar:///home/pi/db-sync/db-sync/src/Command/SyncCommand.php(126): DbSync\Command\SyncCommand->fire()`
`#7 phar:///home/pi/db-sync/db-sync/vendor/symfony/console/Command/Command.php(262): DbSync\Command\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`
`#8 phar:///home/pi/db-sync/db-sync/bin/sync(75): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))`
`#9 phar:///home/pi/db-sync/db-sync/bin/sync(91): DbSync\Command\App->run(Object(DbSync\Command\SyncCommand))`
`#10 /home/pi/db-sync/db-sync(12): require('phar:///home/pi...')`
`#11 {main}`

**Comment by mrjgreen** [comment]
You most likely do not have the pdo_mysql driver installed. You should check the PHP docs for how to do this. 

Cheers
Joe Green

**Comment by mkoivuporras** [comment]
Yes, that was the problem, thank you!
