### ISSUE TITLE
could we sync tables with same host but different port for different db

### ISSUE THREAD

**Issue by halcoolllc** [mrjgreen/db-sync#37]
if so, what is the syntax to do that? thanks. -- Shenghua

**Comment by mrjgreen** [comment]
Like this from example 1 in the read me - simply set the hostnames to be the same, but with different ports, E.G `1.2.3.4:3306` and `1.2.3.4:3307`:

```
# Sync the table web.customers from one host to another (non-standard port on target):

db-sync --user root --password mypass 127.0.0.1 111.222.3.44:13306 web.customers
```
