### ISSUE TITLE
port option

### ISSUE THREAD

**Issue by toby78** [mrjgreen/db-sync#4]
to sync remote database is often done via SSH tunneling - then MySQL can be reached at a different port. The port option is missing?

**Comment by mrjgreen** [comment]
Hey great idea. I'll get that added in!

**Comment by toby78** [comment]
I started with this in my own fork - please have a look. Should not be that much changes needed. Alternatively we could make a port an optional part of the hostname, e.g. 1.2.3.4:3308 as a target database and 1.2.3.5 as a source database (which would default back to 3307).

ssh login@server -L 3306:127.0.0.1:3307 -N

**Comment by mrjgreen** [comment]
Have you tried just specifying the port option in the host param?

db-sync [options] [--] 127.0.0.1:3307 123.32.1.2:3307 <database.table>

The command uses PDO under the hood so it should work...

**Comment by michabbb** [comment]
`hostname:port` does **NOT** work ;(

**Comment by mrjgreen** [comment]
Added port parsing in 650bae6f8d568f07d58b178581f5fcca76121158
