### ISSUE TITLE
Using PHP Non-CommandLine - Sync All tables

### ISSUE THREAD

**Issue by rajendradewani** [mrjgreen/db-sync#41]
Hi 
I am using php page and have added code from the sample.

I am able to sync single table.
I would like to sync all the tables.
Instead of specifying tables names in my php code would it be possible to sync all the tables.

Could you please share a sample code for the same.

**Comment by rene-hermenau** [comment]
@rajendradewani Did you already try to iterate over all tables and use a loop?

```
foreach ($tables as $sourceTable){
      $sourceTable = new Table($sourceConnection, $sourceDb, $sourceTable);

      $targetTable = new Table($targetConnection, $targetDb, 'prefix_' . $sourceTable);
      ...
     $sync->sync($sourceTable, $targetTable);
}
```

**Comment by rajendradewani** [comment]
Thank you @rene-hermenau :-)
This fixed the reported issue.
