### ISSUE TITLE
Delete from source does not sync to Destination

### ISSUE THREAD

**Issue by rajendradewani** [mrjgreen/db-sync#42]
Hi,

I am able to get updated and newly added records to the destination database.

Any record deleted in the source table is not synced to the destination.
the destination database still shows the record which is deleted in the source table.

Is there any settings to delete the records which no longer exists in the source table.
Re-Sync entire table will be a time-consuming process as we will not know when a record is deleted in the source database.

**Comment by mrjgreen** [comment]
https://github.com/mrjgreen/db-sync#notes-about-deletion
