### ISSUE TITLE
Duplicate entry error and question about block-size

### ISSUE THREAD

**Issue by tmtben** [mrjgreen/db-sync#6]
Hi,

First, thanks for your great job!

Question:
What's the block-size used for?

And now, I don't understand why I get this:

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '_site_transient_timeout_poptags_40cd750bba9870f18aada2478b24840a' for key 'option_name'
host: mysql
username: root
charset: utf8
collation: utf8_general_ci
driver: mysql
options.3: 2
options.19: 2
options.20: 
SQL: insert into `mydb`.`wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) values (172, _site_transient_timeout_poptags_40cd750bba9870f18aada2478b24840a, 1448585953, yes), (173, _site_transient_poptags_40cd750bba9870f18aada2478b24840a, a:100:{s:6:"widget";a:3:{s:4:"name";s:6:"widget";s:4:"slug";s:6:"widget";s:5:"count";s:4:"5581";}s:4:"post";a:3:{s:4:"name";s:4:"Post";s:4:"slug";s:4:"post";s:5:"count";s:4:"3497";}s:6:"plugin";a:3:{s:4:"name";s:6:"plugin";s:4:"slug";s:6:"plugin";s:5:"count";s:4:"3449";}s:5:"admin";a:3:{s:4:"name";s:5:"admin";s:4:"slug";s:5:"admin";s:5:"count";s:4:"2960";}s:5:"posts";a:3:{s:4:"name";s:5:"posts";s:4:"slug";s:5:"posts";s:5:"count";s:4:"2696";}s:9:"shortcode";a:3:{s:4:"name";s:9:"shortcode";s:4:"slug";s:9:"shortcode";s:5:"count";s:4:"2149";}s:7:"sidebar";a:3:{s:4:"name";s:7:"sidebar";s:4:"slug";s:7:"sidebar";s:5:"count";s:4:"2142";}s:6:"google";a:3:{s:4:"name";s:6:"google";s:4:"slug";s:6:"google";s:5:"count"  

  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '_site_transient_timeout_poptags_40cd750bba9870f18aada2478b24840a' for key 'option_name'
host: mysql
username: root
charset: utf8
collation: utf8_general_ci
driver: mysql
options.3: 2
options.19: 2
options.20: 
SQL: insert into `mydb`.`wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) values (172, _site_transient_timeout_poptags_40cd750bba9870f18aada2478b24840a, 1448585953, yes), (173, _site_transient_poptags_40cd750bba9870f18aada2478b24840a, a:100:{s:6:"widget";a:3:{s:4:"name";s:6:"widget";s:4:"slug";s:6:"widget";s:5:"count";s:4:"5581";}s:4:"post";a:3:{s:4:"name";s:4:"Post";s:4:"slug";s:4:"post";s:5:"count";s:4:"3497";}s:6:"plugin";a:3:{s:4:"name";s:6:"plugin";s:4:"slug";s:6:"plugin";s:5:"count";s:4:"3449";}s:5:"admin";a:3:{s:4:"name";s:5:"admin";s:4:"slug";s:5:"admin";s:5:"count";s:4:"2960";}s:5:"posts";a:3:{s:4:"name";s:5:"posts";s:4:"slug";s:5:"posts";s:5:"count";s:4:"2696";}s:9:"shortcode";a:3:{s:4:"name";s:9:"shortcode";s:4:"slug";s:9:"shortcode";s:5:"count";s:4:"2149";}s:7:"sidebar";a:3:{s:4:"name";s:7:"sidebar";s:4:"slug";s:7:"sidebar";s:5:"count";s:4:"2142";}s:6:"google";a:3:{s:4:"name";s:6:"google";s:4:"slug";s:6:"google";s:5:"count"  
#0 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Connection.php(360): Database\Exception\ExceptionHandler->handle('insert into `my...', Array, Object(PDOException))
#1 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Connection.php(326): Database\Connection->execute('insert into `my...', Array, false)
#2 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Connection.php(244): Database\Connection->run('insert into `my...', Array)
#3 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Query/Builder.php(1662): Database\Connection->query('insert into `my...', Array)
#4 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Query/Builder.php(1674): Database\Query\Builder->insertUpdate(Array, Array)
#5 phar:///usr/bin/db-sync/src/Table.php(209): Database\Query\Builder->insertOnDuplicateKeyUpdate(Array, Array)
#6 phar:///usr/bin/db-sync/src/DbSync.php(165): DbSync\Table->insert(Array, Array)
#7 phar:///usr/bin/db-sync/src/DbSync.php(115): DbSync\DbSync->copy(Object(DbSync\Table), Object(DbSync\Table), Array, Array, Array)
#8 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 8, Array)
#9 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 16, Array)
#10 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 32, Array)
#11 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 64, Array)
#12 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 128, Array)
#13 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 256, Array)
#14 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 512, Array)
#15 phar:///usr/bin/db-sync/src/DbSync.php(79): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 1024)
#16 phar:///usr/bin/db-sync/src/Command/SyncCommand.php(178): DbSync\DbSync->sync(Object(DbSync\Table), Object(DbSync\Table), Object(DbSync\ColumnConfiguration), Object(DbSync\ColumnConfiguration))
#17 phar:///usr/bin/db-sync/src/Command/SyncCommand.php(110): DbSync\Command\SyncCommand->fire()
#18 phar:///usr/bin/db-sync/vendor/symfony/console/Command/Command.php(259): DbSync\Command\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///usr/bin/db-sync/bin/sync(75): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///usr/bin/db-sync/bin/sync(91): DbSync\Command\App->run(Object(DbSync\Command\SyncCommand))
#21 /usr/bin/db-sync(12): require('phar:///usr/bin...')
#22 {main}
#0 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Connection.php(360): Database\Exception\ExceptionHandler->handle('insert into `my...', Array, Object(PDOException))
#1 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Connection.php(326): Database\Connection->execute('insert into `my...', Array, false)
#2 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Connection.php(244): Database\Connection->run('insert into `my...', Array)
#3 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Query/Builder.php(1662): Database\Connection->query('insert into `my...', Array)
#4 phar:///usr/bin/db-sync/vendor/mrjgreen/database/src/Query/Builder.php(1674): Database\Query\Builder->insertUpdate(Array, Array)
#5 phar:///usr/bin/db-sync/src/Table.php(209): Database\Query\Builder->insertOnDuplicateKeyUpdate(Array, Array)
#6 phar:///usr/bin/db-sync/src/DbSync.php(165): DbSync\Table->insert(Array, Array)
#7 phar:///usr/bin/db-sync/src/DbSync.php(115): DbSync\DbSync->copy(Object(DbSync\Table), Object(DbSync\Table), Array, Array, Array)
#8 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 8, Array)
#9 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 16, Array)
#10 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 32, Array)
#11 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 64, Array)
#12 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 128, Array)
#13 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 256, Array)
#14 phar:///usr/bin/db-sync/src/DbSync.php(118): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 512, Array)
#15 phar:///usr/bin/db-sync/src/DbSync.php(79): DbSync\DbSync->doComparison(Object(DbSync\Table), Object(DbSync\Table), Array, 'CONCAT(COALESCE...', 1024)
#16 phar:///usr/bin/db-sync/src/Command/SyncCommand.php(178): DbSync\DbSync->sync(Object(DbSync\Table), Object(DbSync\Table), Object(DbSync\ColumnConfiguration), Object(DbSync\ColumnConfiguration))
#17 phar:///usr/bin/db-sync/src/Command/SyncCommand.php(110): DbSync\Command\SyncCommand->fire()
#18 phar:///usr/bin/db-sync/vendor/symfony/console/Command/Command.php(259): DbSync\Command\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///usr/bin/db-sync/bin/sync(75): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///usr/bin/db-sync/bin/sync(91): DbSync\Command\App->run(Object(DbSync\Command\SyncCommand))
#21 /usr/bin/db-sync(12): require('phar:///usr/bin...')
#22 {main}

Best regards,
Ben

**Comment by tmtben** [comment]
Here is the log file:
[db-sync.log.txt](https://github.com/mrjgreen/db-sync/files/46792/db-sync.log.txt)

**Comment by tmtben** [comment]
Here is the field value I suspect to be "wrong" (see attached file too):
[field.txt](https://github.com/mrjgreen/db-sync/files/49131/field.txt)

a:100:{s:6:"widget";a:3:{s:4:"name";s:6:"widget";s:4:"slug";s:6:"widget";s:5:"count";s:4:"5581";}s:4:"post";a:3:{s:4:"name";s:4:"Post";s:4:"slug";s:4:"post";s:5:"count";s:4:"3497";}s:6:"plugin";a:3:{s:4:"name";s:6:"plugin";s:4:"slug";s:6:"plugin";s:5:"count";s:4:"3449";}s:5:"admin";a:3:{s:4:"name";s:5:"admin";s:4:"slug";s:5:"admin";s:5:"count";s:4:"2960";}s:5:"posts";a:3:{s:4:"name";s:5:"posts";s:4:"slug";s:5:"posts";s:5:"count";s:4:"2696";}s:9:"shortcode";a:3:{s:4:"name";s:9:"shortcode";s:4:"slug";s:9:"shortcode";s:5:"count";s:4:"2149";}s:7:"sidebar";a:3:{s:4:"name";s:7:"sidebar";s:4:"slug";s:7:"sidebar";s:5:"count";s:4:"2142";}s:6:"google";a:3:{s:4:"name";s:6:"google";s:4:"slug";s:6:"google";s:5:"count";s:4:"1967";}s:7:"twitter";a:3:{s:4:"name";s:7:"twitter";s:4:"slug";s:7:"twitter";s:5:"count";s:4:"1929";}s:6:"images";a:3:{s:4:"name";s:6:"images";s:4:"slug";s:6:"images";s:5:"count";s:4:"1909";}s:4:"page";a:3:{s:4:"name";s:4:"page";s:4:"slug";s:4:"page";s:5:"count";s:4:"1906";}s:8:"comments";a:3:{s:4:"name";s:8:"comments";s:4:"slug";s:8:"comments";s:5:"count";s:4:"1855";}s:5:"image";a:3:{s:4:"name";s:5:"image";s:4:"slug";s:5:"image";s:5:"count";s:4:"1757";}s:8:"facebook";a:3:{s:4:"name";s:8:"Facebook";s:4:"slug";s:8:"facebook";s:5:"count";s:4:"1558";}s:3:"seo";a:3:{s:4:"name";s:3:"seo";s:4:"slug";s:3:"seo";s:5:"count";s:4:"1481";}s:9:"wordpress";a:3:{s:4:"name";s:9:"wordpress";s:4:"slug";s:9:"wordpress";s:5:"count";s:4:"1453";}s:11:"woocommerce";a:3:{s:4:"name";s:11:"woocommerce";s:4:"slug";s:11:"woocommerce";s:5:"count";s:4:"1318";}s:6:"social";a:3:{s:4:"name";s:6:"social";s:4:"slug";s:6:"social";s:5:"count";s:4:"1269";}s:5:"links";a:3:{s:4:"name";s:5:"links";s:4:"slug";s:5:"links";s:5:"count";s:4:"1251";}s:7:"gallery";a:3:{s:4:"name";s:7:"gallery";s:4:"slug";s:7:"gallery";s:5:"count";s:4:"1222";}s:5:"email";a:3:{s:4:"name";s:5:"email";s:4:"slug";s:5:"email";s:5:"count";s:4:"1116";}s:7:"widgets";a:3:{s:4:"name";s:7:"widgets";s:4:"slug";s:7:"widgets";s:5:"count";s:4:"1047";}s:5:"pages";a:3:{s:4:"name";s:5:"pages";s:4:"slug";s:5:"pages";s:5:"count";s:4:"1017";}s:6:"jquery";a:3:{s:4:"name";s:6:"jquery";s:4:"slug";s:6:"jquery";s:5:"count";s:3:"969";}s:5:"media";a:3:{s:4:"name";s:5:"media";s:4:"slug";s:5:"media";s:5:"count";s:3:"927";}s:3:"rss";a:3:{s:4:"name";s:3:"rss";s:4:"slug";s:3:"rss";s:5:"count";s:3:"898";}s:4:"ajax";a:3:{s:4:"name";s:4:"AJAX";s:4:"slug";s:4:"ajax";s:5:"count";s:3:"863";}s:5:"video";a:3:{s:4:"name";s:5:"video";s:4:"slug";s:5:"video";s:5:"count";s:3:"856";}s:7:"content";a:3:{s:4:"name";s:7:"content";s:4:"slug";s:7:"content";s:5:"count";s:3:"853";}s:9:"ecommerce";a:3:{s:4:"name";s:9:"ecommerce";s:4:"slug";s:9:"ecommerce";s:5:"count";s:3:"850";}s:5:"login";a:3:{s:4:"name";s:5:"login";s:4:"slug";s:5:"login";s:5:"count";s:3:"829";}s:10:"javascript";a:3:{s:4:"name";s:10:"javascript";s:4:"slug";s:10:"javascript";s:5:"count";s:3:"788";}s:10:"buddypress";a:3:{s:4:"name";s:10:"buddypress";s:4:"slug";s:10:"buddypress";s:5:"count";s:3:"752";}s:5:"photo";a:3:{s:4:"name";s:5:"photo";s:4:"slug";s:5:"photo";s:5:"count";s:3:"723";}s:7:"youtube";a:3:{s:4:"name";s:7:"youtube";s:4:"slug";s:7:"youtube";s:5:"count";s:3:"717";}s:4:"feed";a:3:{s:4:"name";s:4:"feed";s:4:"slug";s:4:"feed";s:5:"count";s:3:"716";}s:8:"security";a:3:{s:4:"name";s:8:"security";s:4:"slug";s:8:"security";s:5:"count";s:3:"715";}s:4:"link";a:3:{s:4:"name";s:4:"link";s:4:"slug";s:4:"link";s:5:"count";s:3:"710";}s:10:"responsive";a:3:{s:4:"name";s:10:"responsive";s:4:"slug";s:10:"responsive";s:5:"count";s:3:"701";}s:5:"share";a:3:{s:4:"name";s:5:"Share";s:4:"slug";s:5:"share";s:5:"count";s:3:"694";}s:4:"spam";a:3:{s:4:"name";s:4:"spam";s:4:"slug";s:4:"spam";s:5:"count";s:3:"693";}s:10:"e-commerce";a:3:{s:4:"name";s:10:"e-commerce";s:4:"slug";s:10:"e-commerce";s:5:"count";s:3:"675";}s:6:"photos";a:3:{s:4:"name";s:6:"photos";s:4:"slug";s:6:"photos";s:5:"count";s:3:"668";}s:8:"category";a:3:{s:4:"name";s:8:"category";s:4:"slug";s:8:"category";s:5:"count";s:3:"667";}s:5:"embed";a:3:{s:4:"name";s:5:"embed";s:4:"slug";s:5:"embed";s:5:"count";s:3:"638";}s:9:"analytics";a:3:{s:4:"name";s:9:"analytics";s:4:"slug";s:9:"analytics";s:5:"count";s:3:"636";}s:4:"form";a:3:{s:4:"name";s:4:"form";s:4:"slug";s:4:"form";s:5:"count";s:3:"624";}s:3:"css";a:3:{s:4:"name";s:3:"CSS";s:4:"slug";s:3:"css";s:5:"count";s:3:"622";}s:6:"search";a:3:{s:4:"name";s:6:"search";s:4:"slug";s:6:"search";s:5:"count";s:3:"620";}s:9:"slideshow";a:3:{s:4:"name";s:9:"slideshow";s:4:"slug";s:9:"slideshow";s:5:"count";s:3:"617";}s:6:"custom";a:3:{s:4:"name";s:6:"custom";s:4:"slug";s:6:"custom";s:5:"count";s:3:"590";}s:5:"stats";a:3:{s:4:"name";s:5:"stats";s:4:"slug";s:5:"stats";s:5:"count";s:3:"589";}s:6:"slider";a:3:{s:4:"name";s:6:"slider";s:4:"slug";s:6:"slider";s:5:"count";s:3:"580";}s:7:"comment";a:3:{s:4:"name";s:7:"comment";s:4:"slug";s:7:"comment";s:5:"count";s:3:"575";}s:6:"button";a:3:{s:4:"name";s:6:"button";s:4:"slug";s:6:"button";s:5:"count";s:3:"570";}s:4:"menu";a:3:{s:4:"name";s:4:"menu";s:4:"slug";s:4:"menu";s:5:"count";s:3:"565";}s:5:"theme";a:3:{s:4:"name";s:5:"theme";s:4:"slug";s:5:"theme";s:5:"count";s:3:"565";}s:4:"tags";a:3:{s:4:"name";s:4:"tags";s:4:"slug";s:4:"tags";s:5:"count";s:3:"560";}s:9:"dashboard";a:3:{s:4:"name";s:9:"dashboard";s:4:"slug";s:9:"dashboard";s:5:"count";s:3:"559";}s:10:"categories";a:3:{s:4:"name";s:10:"categories";s:4:"slug";s:10:"categories";s:5:"count";s:3:"551";}s:10:"statistics";a:3:{s:4:"name";s:10:"statistics";s:4:"slug";s:10:"statistics";s:5:"count";s:3:"538";}s:6:"mobile";a:3:{s:4:"name";s:6:"mobile";s:4:"slug";s:6:"mobile";s:5:"count";s:3:"519";}s:3:"ads";a:3:{s:4:"name";s:3:"ads";s:4:"slug";s:3:"ads";s:5:"count";s:3:"518";}s:4:"user";a:3:{s:4:"name";s:4:"user";s:4:"slug";s:4:"user";s:5:"count";s:3:"514";}s:6:"editor";a:3:{s:4:"name";s:6:"editor";s:4:"slug";s:6:"editor";s:5:"count";s:3:"506";}s:5:"users";a:3:{s:4:"name";s:5:"users";s:4:"slug";s:5:"users";s:5:"count";s:3:"501";}s:7:"picture";a:3:{s:4:"name";s:7:"picture";s:4:"slug";s:7:"picture";s:5:"count";s:3:"499";}s:4:"list";a:3:{s:4:"name";s:4:"list";s:4:"slug";s:4:"list";s:5:"count";s:3:"495";}s:7:"plugins";a:3:{s:4:"name";s:7:"plugins";s:4:"slug";s:7:"plugins";s:5:"count";s:3:"493";}s:9:"affiliate";a:3:{s:4:"name";s:9:"affiliate";s:4:"slug";s:9:"affiliate";s:5:"count";s:3:"487";}s:9:"multisite";a:3:{s:4:"name";s:9:"multisite";s:4:"slug";s:9:"multisite";s:5:"count";s:3:"464";}s:6:"simple";a:3:{s:4:"name";s:6:"simple";s:4:"slug";s:6:"simple";s:5:"count";s:3:"459";}s:8:"pictures";a:3:{s:4:"name";s:8:"pictures";s:4:"slug";s:8:"pictures";s:5:"count";s:3:"450";}s:12:"contact-form";a:3:{s:4:"name";s:12:"contact form";s:4:"slug";s:12:"contact-form";s:5:"count";s:3:"450";}s:12:"social-media";a:3:{s:4:"name";s:12:"social media";s:4:"slug";s:12:"social-media";s:5:"count";s:3:"442";}s:7:"contact";a:3:{s:4:"name";s:7:"contact";s:4:"slug";s:7:"contact";s:5:"count";s:3:"441";}s:10:"navigation";a:3:{s:4:"name";s:10:"navigation";s:4:"slug";s:10:"navigation";s:5:"count";s:3:"426";}s:5:"flash";a:3:{s:4:"name";s:5:"flash";s:4:"slug";s:5:"flash";s:5:"count";s:3:"420";}s:3:"url";a:3:{s:4:"name";s:3:"url";s:4:"slug";s:3:"url";s:5:"count";s:3:"415";}s:4:"html";a:3:{s:4:"name";s:4:"html";s:4:"slug";s:4:"html";s:5:"count";s:3:"412";}s:10:"newsletter";a:3:{s:4:"name";s:10:"newsletter";s:4:"slug";s:10:"newsletter";s:5:"count";s:3:"403";}s:3:"api";a:3:{s:4:"name";s:3:"api";s:4:"slug";s:3:"api";s:5:"count";s:3:"403";}s:4:"meta";a:3:{s:4:"name";s:4:"meta";s:4:"slug";s:4:"meta";s:5:"count";s:3:"397";}s:4:"shop";a:3:{s:4:"name";s:4:"shop";s:4:"slug";s:4:"shop";s:5:"count";s:3:"396";}s:4:"news";a:3:{s:4:"name";s:4:"News";s:4:"slug";s:4:"news";s:5:"count";s:3:"394";}s:9:"marketing";a:3:{s:4:"name";s:9:"marketing";s:4:"slug";s:9:"marketing";s:5:"count";s:3:"392";}s:3:"tag";a:3:{s:4:"name";s:3:"tag";s:4:"slug";s:3:"tag";s:5:"count";s:3:"390";}s:6:"events";a:3:{s:4:"name";s:6:"events";s:4:"slug";s:6:"events";s:5:"count";s:3:"385";}s:9:"thumbnail";a:3:{s:4:"name";s:9:"thumbnail";s:4:"slug";s:9:"thumbnail";s:5:"count";s:3:"380";}s:8:"tracking";a:3:{s:4:"name";s:8:"tracking";s:4:"slug";s:8:"tracking";s:5:"count";s:3:"379";}s:8:"calendar";a:3:{s:4:"name";s:8:"calendar";s:4:"slug";s:8:"calendar";s:5:"count";s:3:"379";}s:11:"advertising";a:3:{s:4:"name";s:11:"advertising";s:4:"slug";s:11:"advertising";s:5:"count";s:3:"376";}s:4:"text";a:3:{s:4:"name";s:4:"text";s:4:"slug";s:4:"text";s:5:"count";s:3:"376";}s:4:"code";a:3:{s:4:"name";s:4:"code";s:4:"slug";s:4:"code";s:5:"count";s:3:"372";}s:6:"upload";a:3:{s:4:"name";s:6:"upload";s:4:"slug";s:6:"upload";s:5:"count";s:3:"368";}s:8:"lightbox";a:3:{s:4:"name";s:8:"lightbox";s:4:"slug";s:8:"lightbox";s:5:"count";s:3:"367";}s:10:"shortcodes";a:3:{s:4:"name";s:10:"shortcodes";s:4:"slug";s:10:"shortcodes";s:5:"count";s:3:"365";}s:9:"automatic";a:3:{s:4:"name";s:9:"automatic";s:4:"slug";s:9:"automatic";s:5:"count";s:3:"365";}s:7:"sharing";a:3:{s:4:"name";s:7:"sharing";s:4:"slug";s:7:"sharing";s:5:"count";s:3:"363";}s:7:"profile";a:3:{s:4:"name";s:7:"profile";s:4:"slug";s:7:"profile";s:5:"count";s:3:"363";}}

**Comment by mrjgreen** [comment]
Closing as this is a year old. Apologies for the slow response. Please feel free to reopen if this is still something you would like help with.
