### ISSUE TITLE
running as cronjob

### ISSUE THREAD

**Issue by rbro** [mrjgreen/db-sync#8]
Thanks for a great tool.  I had 2 questions related to running db-sync as a cronjob via cli:

1) Is there a way to suppress the output to certain log levels, so that only warnings or errors are printed?

2) I noticed that when an error occurs, the exit code is still 0.  Is it possible to get a non-zero exit code when there is an error?

**Comment by mrjgreen** [comment]
Thanks! I'll look at fixing the error code and also add some -v levels to the options.

Cheers
Joe Green

**Comment by mrjgreen** [comment]
I've added quite options and fixed the error code to return non zero on failure
