### ISSUE TITLE
Dependency issue with symfony/console

### ISSUE THREAD

**Issue by wout** [mrjgreen/db-sync#9]
I would like to use this package but I'm running into dependency issues with symfony/console.
**db-sync** is using `^2.7` and my project is up to date with the latest version (`^3.1`).

Any chance you're upgrading soon?

**Comment by bdahlinger** [comment]
+1 this request.. thanks!

**Comment by Hoya** [comment]
+1

**Comment by nztim** [comment]
+1 and the same with symfony/debug too

**Comment by mrjgreen** [comment]
Updated deps in f6a32d5e1704415751024ba16c5db5c85cf7cf0b
